config/routes.rb
Rails.application.routes.draw do
  get 'movie/index'
  get 'movie/search', as: 'search'

  root 'movie#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def index
  end

  def search
  	query = params[:search]

  	#Get the first page of results and the pagination info
  	current_page = 1
  	result = get_movies_by_title(query, current_page) 
  	@titles = Array.new
  	get_titles(result, @titles)
	total_result_pages = result['total_pages']

	#Check if there other pages and get it, if it exists
  	while current_page < total_result_pages
  		current_page = current_page + 1
  		result = get_movies_by_title(query, current_page) 
  		get_titles(result, @titles)
  	end	

  	@titles = @titles.sort

  end

  def get_titles(movie_data, titles_array)
  	movies = movie_data['data']
  	movies.each do |movie|
  		titles_array.push movie['Title']
  	end
  end

  def get_movies_by_title(query, page)
  	uri_string = 'https://jsonmock.hackerrank.com/api/movies/search/?Title='
  	uri_string.concat(query)
  	uri_string.concat('&page=')
  	uri_string.concat(page.to_s)
  	uri = URI(uri_string)
  	result = Net::HTTP.get(uri) 

  	return JSON.parse(result)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mangaba</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movie/index.html.erb
<%= form_tag(search_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search_query], required: true, placeholder: "Search movies" %>
<%= submit_tag "Search" %>
<% end %>

app/views/movie/search.html.erb
<h1>Movies</h1>
<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <% if @titles.any? %>
        <% for movie in @titles %>
          <div class='movie'>
              <strong> <%= movie %> </strong>
          </div>
        <% end %>
      <% else %>
        <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
      <% end %>
     </tr>       
  </tbody>
</table>